runmode: debug                 # 开发模式, debug, release, test
addr: :8080                  # HTTP绑定端口
name: go_rest              # API Server的名字
url: http://127.0.0.1:8080   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数try的次数
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5

max_workers: 10
max_queue: 10

tls:
  addr: :8081
#  cert: conf/server.crt
#  key: conf/server.key
  cert: conf/qsys.pem
  key: conf/qsys.key
log:
  writers: stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: true
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
# ys_test:ys123456@tcp(47.93.205.0)/qy_shop?charset=utf8&parseTime=true&loc=Local
db:
  name: qy_shop
  addr: 47.93.205.0:3306
  username: ys_test
  password: ys123456
docker_db:
  name: qy_shop
  addr: 47.93.205.0:3306
  username: ys_test
  password: ys123456
